### ISSUE TITLE
Proposal: Rework setup.md to recommednded tools/environment for this lesson

### ISSUE THREAD

**Issue by jduckles** [carpentries-incubator/markdown-intro#5]
I feel like `setup.md` should maybe make some specific recommendations on a Markdown editing and rendering environment that instructors can use with learners (on any of Mac, Windows, or Linux) in this lesson, not confuse learners with a bunch of other resources 🤔. The resources currently there could be moved to a final episode titled "Further Learning Resources" maybe?  

Happy to take on a re-work of `setup.md` once we have a discussion here on what the best multi-platform environment might be. I'm inclined to say something like the split-view of Hackmd / CodiMD / HedgeDoc might be the easiest way to get lerners going. Then we'd have to dicuss with them how they can translate what they've learned into other places, GitHub, local editors etc. 

Thoughts?

**Comment by jduckles** [comment]
Looking through the lesson further I see you're proposing GitHub, Jupyter and HackMD as dependencies for different ways to get setup. I wonder if we can focus on one of these as a lowest-common-denominator of where learners can learn Markdown syntax and immediately see it rendered. For me HackMD closes that loop most readily, followed by Jupyter (although the switching from styled to unstyled as you click in and out of Markdown cells is potentially confusing) and GitHub's preview tab being the least "loop closing" imo. 

Would it be worth focusing this on HackMD / CodiMD / HedgeDoc? 

Perhaps we could pitch a `learnmd.carpentries.org` HedgeDoc instance that wipes all documents weekly or fortnightly so learners can have a practice environment with no setup required (it can be configured to not even require a login).

**Comment by jduckles** [comment]
We might be able to use the demo server at HedgeDoc for this. Having users click [https://demo.hedgedoc.org/new](https://demo.hedgedoc.org/new) would create a unique HedgeDoc page for each of them and drop it into split-view mode. I've sent a note to the HedgeDoc community forum to see if this would be an acceptable use.

**Comment by jduckles** [comment]
They've said it would be no problem! https://community.hedgedoc.org/t/teaching-workshop-use-of-demo-hedgedoc-org/595/2?u=jduckles

**Comment by jsteyn** [comment]
@jduckles, apologies for my absence and lack of response. I've had a busy few weeks. If you are still happy to rework setup.md it would be greatly appreciated. I think your suggestion for going with HedgeDoc is great and would simplify things. We should then put some work in an episode explaining the different options available and places where MarkDown is used, as well as the slight differences and options offered by different platforms.

**Comment by jduckles** [comment]
@jsteyn I've placed a PR in to get the `setup.md` going for HedgeDoc. Happy to help with that extra episode, perhaps it can go at the end? Feel free to @ me when you want my input or help and it will pop into my GitHub notifications. Cheers!

**Comment by jduckles** [comment]
Closing this issue as the PR has been approved.
